"""F5 profile and monitor constants module."""

F5_PROFILES = [
    "/Common/http",
    "/Common/tcp",
    "/Common/udp",
    "/Common/fastL4",
    "/Common/oneconnect",
    "/Common/clientssl",
    "/Common/serverssl",
    "/Common/http-explicit",
    "/Common/socks",
    "/Common/ftp",
    "/Common/radius",
    "/Common/smb",
    "/Common/xml",
    "/Common/diameter",
    "/Common/dns",
    "/Common/ntlm",
    "/Common/sip",
    "/Common/sctp",
    "/Common/fasthttp",
]

F5_MONITORS = [
    "/Common/http",
    "/Common/https",
    "/Common/tcp",
    "/Common/tcp_half_open",
    "/Common/udp",
    "/Common/icmp",
    "/Common/gateway_icmp",
    "/Common/ftp",
    "/Common/ldap",
    "/Common/mysql",
    "/Common/oracle",
    "/Common/postgresql",
    "/Common/smtp",
    "/Common/snmp_dca",
    "/Common/snmp_dca_base",
    "/Common/dns",
    "/Common/external",
    "/Common/firepass",
    "/Common/inband",
    "/Common/mssql",
    "/Common/nntp",
    "/Common/pop3",
    "/Common/radius",
    "/Common/radius_accounting",
    "/Common/real_server",
    "/Common/rpc",
    "/Common/sasp",
    "/Common/scripted",
    "/Common/sip",
    "/Common/soap",
    "/Common/wap",
    "/Common/wmi",
]